// extension/src/dashboard/Onboarding.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function Onboarding() {
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const [saving, setSaving] = useState(false);
  
  const [config, setConfig] = useState({
    transcription_provider: 'local',
    llm_provider: 'ollama',
    transcription_model: '',
    llm_model: '',
    ollama_base_url: 'http://localhost:11434/api/generate',
    openai_api_key: '',
    groq_api_key: '',
    gemini_api_key: '',
    openrouter_api_key: ''
  });

  const handleSave = async () => {
    setSaving(true);
    try {
      const res = await fetch('http://localhost:8000/config', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(config)
      });
      if (res.ok) {
        // Mark onboarding complete in storage
        chrome.storage.local.set({ onboardingComplete: true }, () => {
          navigate('/');
        });
      } else {
        alert('Failed to save settings.');
      }
    } catch (err) {
      alert('Error connecting to backend.');
    }
    setSaving(false);
  };

  return (
    <div className="min-h-screen bg-tally-bg flex flex-col items-center justify-center p-6 animate-in fade-in duration-1000">
      <div className="w-full max-w-2xl bg-white rounded-3xl p-10 md:p-14 shadow-2xl border border-black/5">
        
        {/* Header */}
        <div className="text-center mb-12">
          <div className="w-12 h-12 rounded-full bg-tally-orange mx-auto mb-6 flex items-center justify-center shadow-lg shadow-tally-orange/20">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>
          </div>
          <h1 className="text-5xl font-serif font-bold text-tally-text tracking-tight mb-4">Welcome to WatchNT<span className="text-tally-orange">.</span></h1>
          <p className="text-lg text-black/50 font-medium max-w-md mx-auto">
            Let's configure your AI setup to get you started with private, automated meeting intelligence.
          </p>
        </div>

        {/* Step 1: Transcription */}
        {step === 1 && (
          <div className="space-y-8 animate-in slide-in-from-right-8 duration-500">
            <h2 className="text-2xl font-serif font-bold text-tally-text border-b border-black/5 pb-4">
              Step 1: Audio Transcription
            </h2>
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-bold tracking-wide uppercase text-black/40 mb-2">Provider</label>
                <select 
                  value={config.transcription_provider}
                  onChange={(e) => setConfig({...config, transcription_provider: e.target.value})}
                  className="w-full p-4 bg-tally-bg border border-black/5 rounded-xl text-tally-text font-bold text-lg focus:outline-none focus:border-tally-orange focus:ring-1 focus:ring-tally-orange transition-all appearance-none"
                >
                  <option value="local">Local (Faster-Whisper)</option>
                  <option value="groq">Groq</option>
                  <option value="openai">OpenAI</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-bold tracking-wide uppercase text-black/40 mb-2">Model Name</label>
                <input 
                  type="text" 
                  placeholder={config.transcription_provider === 'local' ? 'base' : config.transcription_provider === 'groq' ? 'whisper-large-v3' : 'whisper-1'}
                  value={config.transcription_model}
                  onChange={(e) => setConfig({...config, transcription_model: e.target.value})}
                  className="w-full p-4 bg-tally-bg border border-black/5 rounded-xl text-tally-text font-bold text-lg focus:outline-none focus:border-tally-orange focus:ring-1 focus:ring-tally-orange transition-all"
                />
              </div>
            </div>
            <button 
              onClick={() => setStep(2)}
              className="w-full py-4 mt-8 bg-tally-card hover:bg-black text-white rounded-full font-bold text-lg transition-all shadow-xl"
            >
              Next Step &rarr;
            </button>
          </div>
        )}

        {/* Step 2: LLM */}
        {step === 2 && (
          <div className="space-y-8 animate-in slide-in-from-right-8 duration-500">
            <h2 className="text-2xl font-serif font-bold text-tally-text border-b border-black/5 pb-4">
              Step 2: AI Summarization
            </h2>
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-bold tracking-wide uppercase text-black/40 mb-2">Provider</label>
                <select 
                  value={config.llm_provider}
                  onChange={(e) => setConfig({...config, llm_provider: e.target.value})}
                  className="w-full p-4 bg-tally-bg border border-black/5 rounded-xl text-tally-text font-bold text-lg focus:outline-none focus:border-tally-orange focus:ring-1 focus:ring-tally-orange transition-all appearance-none"
                >
                  <option value="ollama">Ollama (Local)</option>
                  <option value="groq">Groq</option>
                  <option value="openai">OpenAI</option>
                  <option value="gemini">Google Gemini</option>
                  <option value="openrouter">OpenRouter</option>
                </select>
              </div>
              
              {config.llm_provider === 'ollama' && (
                <div>
                  <label className="block text-sm font-bold tracking-wide uppercase text-black/40 mb-2">Ollama Base URL</label>
                  <input 
                    type="text" 
                    value={config.ollama_base_url}
                    onChange={(e) => setConfig({...config, ollama_base_url: e.target.value})}
                    className="w-full p-4 bg-tally-bg border border-black/5 rounded-xl text-tally-text font-bold text-lg focus:outline-none focus:border-tally-orange focus:ring-1 focus:ring-tally-orange transition-all"
                  />
                </div>
              )}

              {config.llm_provider !== 'ollama' && (
                <div>
                  <label className="block text-sm font-bold tracking-wide uppercase text-black/40 mb-2">{config.llm_provider.toUpperCase()} API Key</label>
                  <input 
                    type="password" 
                    value={(config as any)[`${config.llm_provider}_api_key`]}
                    onChange={(e) => setConfig({...config, [`${config.llm_provider}_api_key`]: e.target.value})}
                    className="w-full p-4 bg-tally-bg border border-black/5 rounded-xl text-tally-text font-bold text-lg focus:outline-none focus:border-tally-orange focus:ring-1 focus:ring-tally-orange transition-all"
                  />
                </div>
              )}

              <div>
                <label className="block text-sm font-bold tracking-wide uppercase text-black/40 mb-2">Model Name</label>
                <input 
                  type="text" 
                  placeholder="e.g. llama3, gpt-4o, gemini-1.5-pro"
                  value={config.llm_model}
                  onChange={(e) => setConfig({...config, llm_model: e.target.value})}
                  className="w-full p-4 bg-tally-bg border border-black/5 rounded-xl text-tally-text font-bold text-lg focus:outline-none focus:border-tally-orange focus:ring-1 focus:ring-tally-orange transition-all"
                />
              </div>
            </div>
            <div className="flex gap-4 mt-8">
              <button 
                onClick={() => setStep(1)}
                className="w-1/3 py-4 bg-white border border-black/10 hover:bg-black/5 text-tally-text rounded-full font-bold text-lg transition-all"
              >
                &larr; Back
              </button>
              <button 
                onClick={handleSave}
                disabled={saving}
                className="w-2/3 py-4 bg-tally-orange hover:bg-black text-white rounded-full font-bold text-lg transition-all shadow-xl shadow-tally-orange/20"
              >
                {saving ? 'Completing Setup...' : 'Complete Setup \u2714'}
              </button>
            </div>
          </div>
        )}
        
      </div>
    </div>
  );
}

// apps/web/src/lib/components/Onboarding.svelte
<script lang="ts">
  import { fade } from 'svelte/transition';
  import { dbStore } from '$lib/stores/db.svelte';

  let { onComplete } = $props<{ onComplete: () => void }>();

  let openaiKey = $state('');
  let isSaving = $state(false);
  let error = $state<string | null>(null);

  async function handleSave() {
    if (!openaiKey.trim()) {
      error = 'Please enter an OpenAI API Key';
      return;
    }

    if (!openaiKey.trim().startsWith('sk-')) {
      error = 'Invalid OpenAI API Key format. Should start with "sk-".';
      return;
    }

    isSaving = true;
    error = null;

    try {
      if (dbStore.settings) {
        await dbStore.settings.set('openai_api_key', openaiKey.trim());
        onComplete();
      } else {
        throw new Error('Settings store is not initialized');
      }
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to save settings';
    } finally {
      isSaving = false;
    }
  }
</script>

<div class="h-full flex flex-col justify-center relative w-full h-full p-6" transition:fade>
  <div class="glass-panel p-8 rounded-2xl max-w-sm mx-auto w-full relative z-10">
    <div class="flex items-center space-x-3 mb-6 justify-center">
      <div class="bg-indigo-500/20 p-3 rounded-xl border border-indigo-500/30">
        <svg class="w-8 h-8 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path></svg>
      </div>
    </div>
    
    <h1 class="text-2xl font-bold text-center text-white mb-2">Welcome to WatchNT</h1>
    <p class="text-sm text-slate-400 text-center mb-8">
      WatchNT runs locally and uses your own API keys for complete privacy and cost control.
    </p>

    <div class="space-y-5">
      <div>
        <label for="openai_key" class="block text-sm font-medium text-slate-300 mb-1.5">OpenAI API Key</label>
        <input 
          type="password" 
          id="openai_key" 
          bind:value={openaiKey}
          placeholder="sk-..." 
          class="block w-full rounded-lg bg-slate-900/50 border border-slate-700 text-white placeholder-slate-500 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm px-4 py-2.5 transition-colors focus:outline-none"
        />
        <p class="mt-2 text-xs text-slate-500">Your key never leaves your browser.</p>
      </div>

      {#if error}
        <div class="text-rose-400 text-sm bg-rose-500/10 p-3 rounded-lg border border-rose-500/20">
          {error}
        </div>
      {/if}

      <button 
        onclick={handleSave}
        disabled={isSaving}
        class="w-full flex justify-center items-center py-3 px-4 border border-transparent rounded-lg shadow-lg text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 transition-all mt-8 hover:shadow-indigo-500/25"
      >
        {#if isSaving}
          <div class="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
        {:else}
          Continue to WatchNT
        {/if}
      </button>
    </div>
  </div>
</div>
